config/routes.rb
Wordz::Application.routes.draw do
  resources :words
  resources :game

  root :to => 'game#index'

end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :word, :spelling
end

app/controllers/api/game_controller.rb
class GameAPIController < ApplicationController

  respond_to :json
  actions :index

  def index
    @words = Word.order("RANDOM()").limit(30)
    render json: @words
  end

end

app/controllers/api/words_controller.rb
class Api::WordsController < InheritedResources::Base

  respond_to :json
  actions :index, :create, :update, :destroy

  def index
    @words = Word.order("RANDOM()").page(params[:page]).per_page(10)
    render json: @words
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.order("RANDOM()").limit(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.order("RANDOM()").limit(30)

    # @words = Word.order("RANDOM()").limit(30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/game/index.html.erb
<div id="game"></div>

app/views/home/index.html.erb
<div id="content">

  <ul id="scoreboard">
    <li id="level">
      level: <span></span>
    </li>

    <li id="total-score">
      total score: <span class="total-score"></span>
    </li>

    <li id="level-score">
      score: <span class="level-score"></span>
    </li>

    <li id="timer">
      <span class="minutes"></span>:<span class="seconds"></span>
    </li>

  </ul>


  <div class="row">
    <ul id="words"></ul>
  </div>

</div>

<div class="level-modal reveal-modal"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wordz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br />
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :correct %><br />
    <%= f.check_box :correct %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<div id="words"></div>

<script type="text/javascript">
  $(function() {
    window.router = new Wordz.Routers.WordsRouter({words: <%= @words.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @word.word %>
</p>

<p>
  <b>Correct:</b>
  <%= @word.correct %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>